# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-10 09:31
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('symbol', models.CharField(default='', max_length=4, verbose_name='Symbol')),
                ('rpc_url', models.CharField(help_text='In the form of http://127.0.0.1:9376', max_length=350, unique=True, verbose_name='RPC url')),
                ('rpc_username', models.CharField(max_length=32, verbose_name='RPC username')),
                ('rpc_password', models.CharField(max_length=50, verbose_name='RPC password')),
                ('info', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='Info')),
            ],
            options={
                'verbose_name': 'Coin daemon',
                'verbose_name_plural': 'Coin daemons',
            },
        ),
        migrations.CreateModel(
            name='CoinAddressIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=35, unique=True, verbose_name='Address')),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.Coin', verbose_name='Coin')),
            ],
            options={
                'verbose_name': 'Coin address in',
                'verbose_name_plural': 'Coin addresses in',
            },
        ),
        migrations.CreateModel(
            name='CoinAddressOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=35, unique=True, verbose_name='Address')),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.Coin', verbose_name='Coin')),
            ],
            options={
                'verbose_name': 'Coin address out',
                'verbose_name_plural': 'Coin addresses out',
            },
        ),
        migrations.CreateModel(
            name='ExchangeTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins_received', models.DecimalField(decimal_places=8, default=0, max_digits=15, verbose_name='Coins received')),
                ('coins_sent', models.DecimalField(decimal_places=8, default=0, max_digits=15, verbose_name='Coins sent')),
                ('rate', models.FloatField(default=0, verbose_name='Rate')),
                ('commission', models.FloatField(default=0, verbose_name='Commission')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Waiting for payment'), (2, 'Payment received'), (3, 'No balance to send payment'), (4, 'Waiting for wallet'), (5, 'Transaction complete')], default=1, verbose_name='Status')),
                ('is_failed', models.BooleanField(default=False)),
                ('error_message', models.CharField(blank=True, default='', max_length=2048, null=True)),
                ('slug', models.SlugField(max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('in_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_address', to='exchange.CoinAddressIn', verbose_name='Pay in address')),
                ('out_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_address', to='exchange.CoinAddressOut', verbose_name='Pay out address')),
            ],
            options={
                'verbose_name': 'Exchange transaction',
                'verbose_name_plural': 'Exchange transactions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('coin_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_from', to='exchange.Coin', verbose_name='Coin from')),
                ('coin_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_to', to='exchange.Coin', verbose_name='Coin to')),
            ],
            options={
                'verbose_name': 'Pair',
                'verbose_name_plural': 'Pairs',
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField(verbose_name='Rate')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.Pair', verbose_name='Pair')),
            ],
            options={
                'verbose_name': 'Rate',
                'verbose_name_plural': 'Rates',
            },
        ),
        migrations.AddField(
            model_name='exchangetransaction',
            name='pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.Pair', verbose_name='Pair'),
        ),
    ]
