# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-10 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_externalrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalrate',
            name='rate',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=15, verbose_name='Rate'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='rate',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=15, verbose_name='Rate'),
        ),
    ]
