# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-11 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0003_auto_20170910_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangetransaction',
            name='rate',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=15, verbose_name='Rate'),
        ),
    ]
