# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-13 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0005_coin_wallet_passphrase'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangetransaction',
            name='confirmations',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Confirmations'),
        ),
    ]
