# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-14 07:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0006_exchangetransaction_confirmations'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=8, default=0, max_digits=15, verbose_name='Balance')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.Coin', verbose_name='Coin')),
            ],
            options={
                'verbose_name_plural': 'Coin balances',
                'verbose_name': 'Coin balance',
            },
        ),
    ]
