# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-14 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0007_coinbalance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinbalance',
            name='balance',
            field=models.FloatField(default=0, verbose_name='Balance'),
        ),
    ]
