# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-14 19:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0008_auto_20170914_0759'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField(max_length=255)),
                ('ip', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='exchangetransaction',
            name='ip',
            field=models.CharField(default=123, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chat',
            name='transaction',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='exchange.ExchangeTransaction'),
        ),
    ]
