# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-17 10:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0010_auto_20170914_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='msg',
            field=models.CharField(max_length=255, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='transaction',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='exchange.ExchangeTransaction', verbose_name='Transaction'),
        ),
    ]
